### ISSUE TITLE
[Feature request] Support WASM import definitions

### ISSUE THREAD

**Issue by orsinium** [RoyalIcing/Orb#34]
Hi Patrick,

Thank you for this amazing project! Wasm lacks functional languages and interpreted languages, and Elixir is both.

I'm working on [Firefly Zero](https://fireflyzero.com/) a FOSS handheld game console running WebAssembly. It's in the early stages but you can already make games for it and try out the ones we have. I want to make an official SDK for Firefly Zero using Orb, making it possible to write retro games with Elixir. All I need is a way to define [wasm imports](https://webassembly.github.io/spec/core/syntax/modules.html#imports) for functions (and exports as well but it seems like you already support it with `defw`). From reading the docs, looks like there is no way to do that yet. Is it something you'd be interested in implementing?

**Comment by RoyalIcing** [comment]
That sounds like a great project! I hope more independent hardware makers come into the world.

Imports are supported, and your issue prompted me to make the syntax better in `0.0.46`.

The docs for `Orb.Import` are [here](https://hexdocs.pm/orb/Orb.Import.html). Let me know if they suffice, I will keep improving things until they are clear.

Let me know how else I can help, and looking forward to having an SDK — that sounds awesome!

**Comment by orsinium** [comment]
I've got it working! Thank you, the new API is indeed better. I'll let you know when I have a fully working SDK, now it's just a matter of time :)

![image](https://github.com/RoyalIcing/Orb/assets/9638362/62dc8121-c385-4838-971d-5a65021bf14e)

**Comment by RoyalIcing** [comment]
That’s incredible! Any hitches or things you think could be better let me know! I won’t be offended if you say “this sucks, can you make it better”.

**Comment by orsinium** [comment]
> Any hitches or things you think could be better let me know! 

I sure will! I have only one blocker so far:
https://github.com/RoyalIcing/Orb/issues/36

Other than that, the SDK for graphics is ready:
https://github.com/firefly-zero/firefly-elixir

I've published it in your Show & Tell:
https://github.com/RoyalIcing/Orb/discussions/37
